In [3]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [9]:
data=pd.read_csv("jobs_in_data.csv")
data

work_year                 job_title                    job_category  \
0          2023      Data DevOps Engineer                Data Engineering   
1          2023            Data Architect  Data Architecture and Modeling   
2          2023            Data Architect  Data Architecture and Modeling   
3          2023            Data Scientist       Data Science and Research   
4          2023            Data Scientist       Data Science and Research   
...         ...                       ...                             ...   
9350       2021           Data Specialist    Data Management and Strategy   
9351       2020            Data Scientist       Data Science and Research   
9352       2021  Principal Data Scientist       Data Science and Research   
9353       2020            Data Scientist       Data Science and Research   
9354       2020     Business Data Analyst                   Data Analysis   

     salary_currency  salary  salary_in_usd employee_residence  \
0                EUR   88000          95012            Germany   
1                USD  186000         186000      United States   
2                USD   81800          81800      United States   
3                USD  212000         212000      United States   
4                USD   93300          93300      United States   
...              ...     ...            ...                ...   
9350             USD  165000         165000      United States   
9351             USD  412000         412000      United States   
9352             USD  151000         151000      United States   
9353             USD  105000         105000      United States   
9354             USD  100000         100000      United States   

     experience_level employment_type work_setting company_location  \
0           Mid-level       Full-time       Hybrid          Germany   
1              Senior       Full-time    In-person    United States   
2              Senior       Full-time    In-person    United States   
3              Senior       Full-time    In-person    United States   
4              Senior       Full-time    In-person    United States   
...               ...             ...          ...              ...   
9350           Senior       Full-time       Remote    United States   
9351           Senior       Full-time       Remote    United States   
9352        Mid-level       Full-time       Remote    United States   
9353      Entry-level       Full-time       Remote    United States   
9354      Entry-level        Contract       Remote    United States   

     company_size  
0               L  
1               M  
2               M  
3               M  
4               M  
...           ...  
9350            L  
9351            L  
9352            L  
9353            S  
9354            L  

[9355 rows x 12 columns]

In [11]:
x= data[['work_year','job_title','job_category','salary_currency','salary']].values
x

array([[2023, 'Data DevOps Engineer', 'Data Engineering', 'EUR', 88000],
       [2023, 'Data Architect', 'Data Architecture and Modeling', 'USD',
        186000],
       [2023, 'Data Architect', 'Data Architecture and Modeling', 'USD',
        81800],
       ...,
       [2021, 'Principal Data Scientist', 'Data Science and Research',
        'USD', 151000],
       [2020, 'Data Scientist', 'Data Science and Research', 'USD',
        105000],
       [2020, 'Business Data Analyst', 'Data Analysis', 'USD', 100000]],
      dtype=object)

In [13]:
y=data[['experience_level']].values
y

array([['Mid-level'],
       ['Senior'],
       ['Senior'],
       ...,
       ['Mid-level'],
       ['Entry-level'],
       ['Entry-level']], dtype=object)

In [15]:
print(data.isnull().sum())

work_year             0
job_title             0
job_category          0
salary_currency       0
salary                0
salary_in_usd         0
employee_residence    0
experience_level      0
employment_type       0
work_setting          0
company_location      0
company_size          0
dtype: int64


In [33]:
#imputer =SimpleImputer(missing_values=np.nan,strategy='mean')
#imputer=imputer.fit(x[:,5:6])
label_encoder_x=LabelEncoder()
label_encoder_y=LabelEncoder()
x[:,0]=label_encoder_x.fit_transform(x[:,0])
x

array([[3, 'Data DevOps Engineer', 'Data Engineering', 'EUR', 88000],
       [3, 'Data Architect', 'Data Architecture and Modeling', 'USD',
        186000],
       [3, 'Data Architect', 'Data Architecture and Modeling', 'USD',
        81800],
       ...,
       [1, 'Principal Data Scientist', 'Data Science and Research',
        'USD', 151000],
       [0, 'Data Scientist', 'Data Science and Research', 'USD', 105000],
       [0, 'Business Data Analyst', 'Data Analysis', 'USD', 100000]],
      dtype=object)

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[3, 'Director of Data Science', 'Data Science and Research',
        'USD', 336400],
       [3, 'Research Scientist', 'Data Science and Research', 'USD',
        184700],
       [3, 'Data Analyst', 'Data Analysis', 'EUR', 55000],
       ...,
       [3, 'Data Architect', 'Data Architecture and Modeling', 'USD',
        81800],
       [3, 'Data Analyst', 'Data Analysis', 'USD', 94100],
       [3, 'Data Analyst', 'Data Analysis', 'USD', 167000]], dtype=object)

In [41]:
y_train

array([['Executive'],
       ['Senior'],
       ['Mid-level'],
       ...,
       ['Senior'],
       ['Mid-level'],
       ['Mid-level']], dtype=object)